config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"
  resources :goals
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/goal.rb
class Goal << ApplicationRecord
  has_many :tasks
end

app/models/task.rb
class Task << ApplicationRecord
  belongs_to :goal
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, :last_name, :password, :password_confirmation,
  presence: true

  validates :email, format: {with: /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/}

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(users)
    goals_path
  end

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_out_path_for(users)
    root_path
  end

  def after_update_path_for(users)
    root_path
  end

  protected


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email, :password, :password_confirmation])
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def index
    @goals = Goal.all
  end

  def new
    @goal = Goal.new
  end

  def create
    @goal = Goal.new(goal_params)
    if @goal.safe
      flash[:notice] = "New goal created!"
      redirect_to goals_path
    else
      flash[:alert] = "Goal not created"
      reder :new
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])
    if @goal.save
      flash[:notice] = "Goal updated!"
      @goal.update(goal_params)
      redirect_to goals_path
    else
      flash[:alert] = "Goal not updated"
      render :edit
    end

    def show
      @goal = Goal.find(params[:id])
      @task = Task.where(goal_id = @goal)
    end
  end

  private

  def goal_params
    params.require(:goal).permit(
      :wish,
      :outcome,
      :obstacle
    )
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/goals/index.html.erb
<h1>Welcome To Your Goal Dashboard</h1>
<%= link_to 'Create A Goal', new_goal_path %>

app/views/goals/new.html.erb
<h2>Create Your Number One Goal</h2>

<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>

  <div class="field">
    <%= f.label :wish %><br />
    <%= f.text_field :wish, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :outcome %><br />
    <%= f.text_area :outcome, autofocus: true, size: "24x6" %>
  </div>

  <div class="field">
    <%= f.label :obstacle %><br />
    <%= f.text_area :obstacle, autofocus: true, size: "24x6" %>
  </div>

  <div class="field">
    <%= f.label :task %><br />
    <%= f.text_field :task, autofocus: true %>
  </div>


  <br>

  <div class="actions">
    <%= f.submit "Create Goal" %>
  </div>
<% end %>

<hr>

<%= render "devise/shared/links" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>+1 Goals</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application.js" %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

    <nav class="head_nav">
      <% if !user_signed_in? %>
        <%= link_to 'Sign Up', new_user_registration_path %>
        <%= link_to 'Sign In',  new_user_session_path %>
      <% else %>
        <%= link_to 'Dashboard', goals_path %>
        <%= link_to 'My Account', edit_user_registration_path %>
        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
        <%= link_to 'Contact', '#' %>
      <% end %>
    </nav>

  </head>

  <body>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
  </body>

  <footer>
    <nav class="foot_nav">
      <% if !user_signed_in? %>
        <%= link_to 'Sign Up', new_user_registration_path %>
        <%= link_to 'Sign In',  new_user_session_path %>
      <% else %>
        <%= link_to 'Dashboard', goals_path %>
        <%= link_to 'My Account', edit_user_registration_path %>
        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
        <%= link_to 'Contact', '#' %>
      <% end %>
    </nav>
  </footer>
</html>

app/views/welcome/index.html.erb
<div class='jumbotron'>
  <div class="logo">
    <%= image_tag("logos/plusonegoalslogo.png", :alt => "+1 Logo") %>
  </div>
  <h3>Plan, Track And Achieve</h3>
</div>

<div class="about">
  <h3>Goals are easy to start, hard to maintain. According to the University of Scranton,
    92% of people say they never reach their New Year's goals.</h3>
  <h3>So we looked at works,
    and what doesn't work and created an app that uses the latest research
    in achieving success.</h3>
</div>

<div class='features'>
  <h1>+1 Goals? What Is It About?</h1>
</div>

<div class='feature_box'>
  <div class="bullet_points">
    <%= image_tag("icons/checkmark.png") %>
  </div>
    <div class="row">
      <div class="col-sm-4">
        <div class="icon">
          <%= image_tag("icons/plan.png") %>
        </div>
          <h3>Plan With The End In Mind</h3>
          <p>With every goal you set, we use backwards planning.</p>
          <p>We break down each step required and create a task.</p>
          <p>Easily add that task to your daily to-do list app or calendar.</p>
      </div>

    <div class="col-sm-4">
      <div class="icon">
        <%= image_tag("icons/target.png") %>
      </div>
      <h3>+1 Every Task Completed</h3>
      <p>The objective is to get as many +1's you can each day.</p>
      <p>Break down tasks into subtasks so you know exactly what you need to accomplish.</p>
      <p>Keep track of your progress with ease and know exactly what you have to do next.</p>
    </div>

    <div class="col-sm-4">
      <div class="icon">
        <%= image_tag("icons/graph.png") %>
      </div>
      <h3>Success When You Add It All Up</h3>
      <p>The name of the game is to get as many +1's as you can each day.</p>
      <p>When you add up all the +1's, that's when you reached your goal.</p>
    </div>
  </div>
</div>

<div class='signup'>
  <%= button_to "Sign Up", new_user_registration_path, :method => "get" %>
</div>
<br><br>